# Generated by Django 6.0.5 on 2026-05-30 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pft', '0002_alter_expense_created_at_alter_income_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', '-created_at'], name='expense_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', '-created_at'], name='income_user_date_idx'),
        ),
    ]
